import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Slideshow from "@/components/Slideshow/Slideshow";
import Companies from "@/components/Companies/Companies";

export default function Home() {
  return (
    <>
      <Head>
        <title>Garry Motors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="garry1.jpg" />
      </Head>
      <main>
        <Slideshow />
        <Companies />
        <img src="working.png" alt="" className={styles.image}/>
        <img src="workings1.png" alt="" className={styles.images} />
        <img src="workings2.png" alt="" className={styles.images} />
        <img src="about.png" alt="" className={styles.image2} />
        <img src="abouts.png" alt="" className={styles.images2} />
        <img src="contact.png" alt="" className={styles.imagec}/>
      </main>
    </>
  );
}
